# Generated by Django 5.2.8 on 2025-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profiles_work_field_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
