# Generated by Django 5.2.8 on 2025-11-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoInto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DashName', models.CharField(max_length=20)),
                ('DashIMG', models.ImageField(upload_to='GoInto/')),
            ],
        ),
    ]
