# Generated by Django 5.2.8 on 2025-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_gointo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='work_flow',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('videoEditer', 'Video Editor'), ('AccountFinace', 'Account Finace'), ('websitedesign', 'Website Design'), ('HR', 'Human Resource'), ('software', 'Software Engineering')], max_length=30, null=True),
        ),
    ]
