# Generated by Django 5.2.8 on 2025-11-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profiles_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='profile_img',
            new_name='user_profile_img',
        ),
    ]
