# Generated by Django 5.2.8 on 2025-11-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_profile_img_profiles_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='work_field_flows',
        ),
    ]
