# Generated by Django 5.2.8 on 2025-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='userProfile',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_picture/'),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
