# Generated by Django 5.2.8 on 2025-11-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_profiles_userprofile_delete_profilepicture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
