# Generated by Django 5.2.8 on 2025-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_accountinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
    ]
