# Generated by Django 5.2.8 on 2025-12-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_accountinfo_email_accountinfo_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='password2',
        ),
    ]
