# Generated by Django 5.2.8 on 2025-12-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_accountinfo_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountInfo',
        ),
    ]
