# Generated by Django 5.2.8 on 2025-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_profiles_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
