# Generated by Django 5.2.8 on 2025-12-05 14:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_remove_user_password1_remove_user_password2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='date_modify',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='profiles',
            name='follow_suggetion',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='Accounts.profiles'),
        ),
    ]
