# Generated by Django 5.2.8 on 2025-12-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_profiles_date_modify_profiles_follow_suggetion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='date_modify',
            new_name='last_seen',
        ),
    ]
