# Generated by Django 5.2.8 on 2025-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_rename_date_modify_profiles_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
