# Generated by Django 5.2.8 on 2025-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_alter_profiles_last_seen_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='note_forms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
