# Generated by Django 5.2.8 on 2025-12-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_profiles_note_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='note_forms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
