# Generated by Django 5.2.8 on 2025-12-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_profiles_note_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make_Publish_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Discription', models.TextField(blank=True, null=True)),
                ('Publish_IMG', models.ImageField(upload_to='UserPost/Published')),
                ('Rate', models.IntegerField()),
                ('Messages', models.CharField(max_length=255)),
            ],
        ),
    ]
