# Generated by Django 5.2.8 on 2025-12-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_account_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_publish_post',
            name='working_fields',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('videoEditer', 'Video Editor'), ('AccountFinace', 'Account Finace'), ('websitedesign', 'Website Design'), ('HR', 'Human Resource'), ('software', 'Software Engineering')], null=True),
        ),
    ]
