# Generated by Django 5.2.8 on 2025-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_make_publish_post_working_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_publish_post',
            name='working_fields',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('videoEditer', 'Video Editor'), ('AccountFinace', 'Account Finace'), ('websitedesign', 'Website Design'), ('HR', 'Human Resource'), ('software', 'Software Engineering')], default='None', null=True),
        ),
    ]
