# Generated by Django 5.2.8 on 2025-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_alter_make_publish_post_working_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_publish_post',
            name='Messages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='make_publish_post',
            name='Rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
