# Generated by Django 5.2.8 on 2025-12-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_alter_make_publish_post_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_publish_post',
            name='create_info',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
