# Generated by Django 5.2.8 on 2026-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_make_publish_post_create_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Post_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Publish/Post/Image'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Post_discrition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Post_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
