# Generated by Django 5.2.8 on 2026-01-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_profiles_post_image_profiles_post_discrition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_publish_post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profiles'),
        ),
        migrations.AlterField(
            model_name='make_publish_post',
            name='Publish_IMG',
            field=models.ImageField(blank=True, null=True, upload_to='UserPost/Published'),
        ),
        migrations.AlterField(
            model_name='make_publish_post',
            name='working_fields',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('videoEditer', 'Video Editor'), ('AccountFinace', 'Account Finace'), ('websitedesign', 'Website Design'), ('HR', 'Human Resource'), ('software', 'Software Engineering')], default='draft', null=True),
        ),
    ]
