# Generated by Django 5.2.8 on 2026-01-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0032_make_publish_post_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_publish_post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profiles'),
        ),
    ]
