# Generated by Django 6.0.1 on 2026-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_make_publish_post_view_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='Post_Image',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='Post_discrition',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='Post_title',
        ),
        migrations.AlterField(
            model_name='make_publish_post',
            name='view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
