# Generated by Django 6.0.1 on 2026-01-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_remove_profiles_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_Page_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_info', models.DateField(auto_created=True, auto_now_add=True, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('Discription', models.TextField(blank=True, null=True)),
                ('Publish_IMG', models.ImageField(blank=True, null=True, upload_to='UserPost/Published')),
                ('working_fields', models.CharField(blank=True, choices=[('website', 'Website'), ('videoEditer', 'Video Editor'), ('AccountFinace', 'Account Finace'), ('websitedesign', 'Website Design'), ('HR', 'Human Resource'), ('software', 'Software Engineering')], default='draft', null=True)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Messages', models.CharField(blank=True, max_length=255, null=True)),
                ('view', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profiles')),
            ],
        ),
    ]
