# Generated by Django 6.0.1 on 2026-01-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_publish_page_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish_page_model',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profiles'),
        ),
    ]
