# Generated by Django 6.0.1 on 2026-01-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0037_alter_publish_page_model_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish_page_model',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profiles'),
        ),
    ]
