# Generated by Django 6.0.1 on 2026-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0040_follow_counter_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow_counter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
